---
language: python

env:
  - IMAGE=ubuntu TAG=xenial
  - IMAGE=ubuntu TAG=bionic

dist: xenial
sudo: required

cache: pip

before_install:
  - docker version
  - docker pull $IMAGE:$TAG
  - docker run --name test -di $IMAGE:$TAG /bin/sh
  - docker exec test apt-get update
  - docker exec test apt-get install -y python ca-certificates

install:
  - pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../' | tee ansible.cfg
  - pip install ansible-lint
  - ansible-lint --version

script:
  - ansible-playbook -i localhost, --syntax-check tests/test.yml
  - ansible-lint tests/test.yml
  - ansible-playbook -i test, tests/test.yml
